[phases.setup]
nixPkgs = ["ffmpeg", "python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "pip install yt-dlp spotdl gallery-dl --break-system-packages",
  "npm ci"
]

[start]
cmd = "npm start"